"""
app.py — Iran Conflict Economic Impact Dashboard
Reads CSVs from ./output/ (generated by war_dashboard_data.py).
Run: python app.py
"""

import os
import pandas as pd
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import dash
from dash import dcc, html, Input, Output
import dash_bootstrap_components as dbc

# ─────────────────────────────────────────────────────────────────────────────
# CONSTANTS
# ─────────────────────────────────────────────────────────────────────────────
CONFLICT_START = "2025-10-01"
OUTPUT_DIR = "./output"

BG_PAGE  = "#0d0d0d"
BG_CARD  = "#1a1a1a"
BG_CHART = "#111111"
TEXT     = "#e8e8e8"
TEXT_DIM = "#777777"
RED      = "#E24B4A"
BLUE     = "#378ADD"
GRID     = "#2a2a2a"
BORDER   = "#2e2e2e"

# Base chart layout applied to all figures
CHART_BASE = dict(
    paper_bgcolor=BG_CHART,
    plot_bgcolor=BG_CHART,
    font=dict(family="system-ui, -apple-system, sans-serif", color=TEXT, size=12),
    margin=dict(l=50, r=20, t=30, b=40),
    legend=dict(bgcolor="rgba(0,0,0,0)", bordercolor=BORDER, font=dict(size=11)),
    hoverlabel=dict(bgcolor="#222", bordercolor=BORDER, font_color=TEXT),
)

# ─────────────────────────────────────────────────────────────────────────────
# DATA LOADING  (at startup — no live API calls in the app)
# ─────────────────────────────────────────────────────────────────────────────
def load_csv(filename):
    path = os.path.join(OUTPUT_DIR, filename)
    if not os.path.exists(path):
        return pd.DataFrame()
    df = pd.read_csv(path, index_col="date", parse_dates=True)
    df.index = pd.to_datetime(df.index)
    return df


energy_df  = load_csv("energy_commodities.csv")
equity_df  = load_csv("equity_indices.csv")
vol_df     = load_csv("volatility_rates_fx.csv")
rates_df   = load_csv("us_rates_spreads.csv")
indexed_df = load_csv("all_series_indexed.csv")
wide_df    = load_csv("all_series_wide.csv")

# Date bounds across all available data
_all_indexes = [df.index for df in [wide_df, indexed_df, energy_df, equity_df, vol_df] if not df.empty]
if _all_indexes:
    _combined = _all_indexes[0]
    for ix in _all_indexes[1:]:
        _combined = _combined.union(ix)
    DATE_MIN = _combined.min()
    DATE_MAX = _combined.max()
else:
    DATE_MIN = pd.Timestamp(CONFLICT_START) - pd.Timedelta(days=90)
    DATE_MAX = pd.Timestamp.today()

LAST_UPDATE = DATE_MAX.strftime("%b %d, %Y")

# ─────────────────────────────────────────────────────────────────────────────
# KPI HELPERS
# ─────────────────────────────────────────────────────────────────────────────
def safe_last(df, col, as_of=None):
    """Return the last non-null value of df[col], optionally up to as_of date."""
    if df.empty or col not in df.columns:
        return None
    s = df[col].dropna()
    if as_of is not None:
        s = s[s.index <= pd.Timestamp(as_of)]
    return float(s.iloc[-1]) if not s.empty else None


def safe_d0_val(df, col):
    """Return the first value of df[col] on or after CONFLICT_START."""
    if df.empty or col not in df.columns:
        return None
    post = df.loc[df.index >= pd.Timestamp(CONFLICT_START), col].dropna()
    return float(post.iloc[0]) if not post.empty else None


def delta_pct(current, d0):
    if current is None or d0 is None or d0 == 0:
        return None
    return (current - d0) / abs(d0) * 100


def fmt_delta(v, is_bps=False):
    if v is None:
        return "N/A"
    return f"{v:+.0f} bps" if is_bps else f"{v:+.1f}%"


def risk_color(v, higher_is_bad=True):
    """Red if adverse, blue if beneficial. Returns TEXT_DIM for None."""
    if v is None:
        return TEXT_DIM
    return RED if (v > 0) == higher_is_bad else BLUE


# ── Compute KPI cards at load time ──────────────────────────────────────────
def _compute_kpis():
    kpis = {}

    # Brent — higher oil = bad (conflict risk)
    v = safe_last(energy_df, "brent_usd")
    d = safe_last(energy_df, "brent_usd_delta_vs_d0_pct")
    kpis["brent"] = (f"{v:.2f}" if v else "N/A", fmt_delta(d), risk_color(d, True))

    # Gold — higher gold = safe-haven (blue = good signal)
    v = safe_last(energy_df, "gold_usd")
    d = safe_last(energy_df, "gold_usd_delta_vs_d0_pct")
    kpis["gold"] = (f"{v:,.0f}" if v else "N/A", fmt_delta(d), risk_color(d, False))

    # VIX — higher = more fear = bad
    v = safe_last(vol_df, "vix")
    d = safe_last(vol_df, "vix_delta_vs_d0_pct")
    kpis["vix"] = (f"{v:.1f}" if v else "N/A", fmt_delta(d), risk_color(d, True))

    # DXY — higher = USD strengthening = risk-off signal
    v = safe_last(vol_df, "dxy")
    d = safe_last(vol_df, "dxy_delta_vs_d0_pct")
    kpis["dxy"] = (f"{v:.1f}" if v else "N/A", fmt_delta(d), risk_color(d, True))

    # US 10Y — delta in basis points
    v   = safe_last(rates_df, "us10y_yield")
    d0  = safe_d0_val(rates_df, "us10y_yield")
    bps = (v - d0) * 100 if v and d0 else None
    kpis["us10y"] = (f"{v:.2f}%" if v else "N/A", fmt_delta(bps, True), risk_color(bps, True))

    # 2Y-10Y spread — wider spread can indicate growth expectations
    if (not rates_df.empty
            and "us10y_yield" in rates_df.columns
            and "us2y_yield" in rates_df.columns):
        merged = rates_df[["us10y_yield", "us2y_yield"]].dropna()
        if not merged.empty:
            spread = merged["us10y_yield"] - merged["us2y_yield"]
            v_bps  = float(spread.iloc[-1]) * 100
            post   = spread[spread.index >= pd.Timestamp(CONFLICT_START)]
            d0_bps = float(post.iloc[0]) * 100 if not post.empty else None
            delta  = (v_bps - d0_bps) if d0_bps is not None else None
            kpis["spread"] = (f"{v_bps:.0f} bps", fmt_delta(delta, True), risk_color(delta, False))
        else:
            kpis["spread"] = ("N/A", "N/A", TEXT_DIM)
    else:
        kpis["spread"] = ("N/A", "N/A", TEXT_DIM)

    return kpis


KPIS = _compute_kpis()

# ─────────────────────────────────────────────────────────────────────────────
# INDEXED SERIES — metadata for dropdown and chart colors
# ─────────────────────────────────────────────────────────────────────────────
SERIES_META = {
    "brent_usd_indexed_d0":   {"label": "Brent",        "color": "#E24B4A"},
    "wti_usd_indexed_d0":     {"label": "WTI",           "color": "#FF7B54"},
    "natgas_usd_indexed_d0":  {"label": "Nat Gas",       "color": "#FFB347"},
    "gold_usd_indexed_d0":    {"label": "Gold",          "color": "#FFD700"},
    "silver_usd_indexed_d0":  {"label": "Silver",        "color": "#C0C0C0"},
    "sp500_indexed_d0":       {"label": "S&P 500",       "color": "#378ADD"},
    "nasdaq_indexed_d0":      {"label": "Nasdaq",        "color": "#5B9BD5"},
    "eurostoxx50_indexed_d0": {"label": "Euro Stoxx 50", "color": "#85C1E9"},
    "dax_indexed_d0":         {"label": "DAX",           "color": "#AED6F1"},
    "ftse100_indexed_d0":     {"label": "FTSE 100",      "color": "#76D7C4"},
    "nikkei225_indexed_d0":   {"label": "Nikkei 225",    "color": "#A9DFBF"},
    "shanghai_indexed_d0":    {"label": "Shanghai",      "color": "#F9E79F"},
    "vix_indexed_d0":         {"label": "VIX",           "color": "#BB8FCE"},
    "dxy_indexed_d0":         {"label": "DXY",           "color": "#F0B27A"},
    "eurusd_indexed_d0":      {"label": "EUR/USD",       "color": "#82E0AA"},
    "jpyusd_indexed_d0":      {"label": "JPY/USD",       "color": "#F1948A"},
}

_avail = [c for c in SERIES_META if not indexed_df.empty and c in indexed_df.columns]
INDEXED_OPTIONS = [{"label": SERIES_META[c]["label"], "value": c} for c in _avail]
DEFAULT_INDEXED  = [c for c in [
    "brent_usd_indexed_d0", "sp500_indexed_d0",
    "gold_usd_indexed_d0",  "dxy_indexed_d0", "vix_indexed_d0",
] if c in _avail]

# ─────────────────────────────────────────────────────────────────────────────
# TABLE — variable definitions
# ─────────────────────────────────────────────────────────────────────────────
TABLE_VARS = [
    {"col": "brent_usd",     "label": "Brent Crude",    "src": energy_df,  "bad_up": True,  "fmt": ".2f"},
    {"col": "wti_usd",       "label": "WTI Crude",      "src": energy_df,  "bad_up": True,  "fmt": ".2f"},
    {"col": "natgas_usd",    "label": "Natural Gas",    "src": energy_df,  "bad_up": True,  "fmt": ".3f"},
    {"col": "gold_usd",      "label": "Gold ($/oz)",    "src": energy_df,  "bad_up": False, "fmt": ",.0f"},
    {"col": "silver_usd",    "label": "Silver ($/oz)",  "src": energy_df,  "bad_up": False, "fmt": ".2f"},
    {"col": "sp500",         "label": "S&P 500",        "src": equity_df,  "bad_up": False, "fmt": ",.0f"},
    {"col": "nasdaq",        "label": "Nasdaq",         "src": equity_df,  "bad_up": False, "fmt": ",.0f"},
    {"col": "eurostoxx50",   "label": "Euro Stoxx 50",  "src": equity_df,  "bad_up": False, "fmt": ",.0f"},
    {"col": "dax",           "label": "DAX",            "src": equity_df,  "bad_up": False, "fmt": ",.0f"},
    {"col": "ftse100",       "label": "FTSE 100",       "src": equity_df,  "bad_up": False, "fmt": ",.0f"},
    {"col": "nikkei225",     "label": "Nikkei 225",     "src": equity_df,  "bad_up": False, "fmt": ",.0f"},
    {"col": "shanghai",      "label": "Shanghai Comp.", "src": equity_df,  "bad_up": False, "fmt": ",.0f"},
    {"col": "vix",           "label": "VIX",            "src": vol_df,     "bad_up": True,  "fmt": ".1f"},
    {"col": "dxy",           "label": "DXY",            "src": vol_df,     "bad_up": True,  "fmt": ".1f"},
    {"col": "eurusd",        "label": "EUR/USD",        "src": vol_df,     "bad_up": False, "fmt": ".4f"},
    {"col": "jpyusd",        "label": "JPY/USD",        "src": vol_df,     "bad_up": True,  "fmt": ".2f"},
    {"col": "us10y_yield",   "label": "US 10Y Yield",   "src": rates_df,   "bad_up": True,  "fmt": ".2f"},
    {"col": "us2y_yield",    "label": "US 2Y Yield",    "src": rates_df,   "bad_up": True,  "fmt": ".2f"},
    {"col": "fed_funds_rate","label": "Fed Funds Rate", "src": rates_df,   "bad_up": True,  "fmt": ".2f"},
    {"col": "embi_spread",   "label": "EMBI+ Spread",   "src": rates_df,   "bad_up": True,  "fmt": ".0f"},
]

# ─────────────────────────────────────────────────────────────────────────────
# APP INIT
# ─────────────────────────────────────────────────────────────────────────────
app = dash.Dash(
    __name__,
    external_stylesheets=[dbc.themes.BOOTSTRAP],
    title="Iran Conflict Dashboard",
    meta_tags=[{"name": "viewport", "content": "width=device-width, initial-scale=1"}],
)
server = app.server  # exposed for gunicorn

# ─────────────────────────────────────────────────────────────────────────────
# LAYOUT COMPONENTS
# ─────────────────────────────────────────────────────────────────────────────
def kpi_card(title, value, delta, color):
    return dbc.Col(
        html.Div([
            html.P(title,  className="kpi-label"),
            html.P(value,  className="kpi-value"),
            html.P(f"vs D0: {delta}", className="kpi-delta", style={"color": color}),
        ], className="kpi-card"),
        xs=6, sm=4, md=2,
    )


app.layout = dbc.Container(fluid=True,
    style={"background": BG_PAGE, "minHeight": "100vh", "padding": "0 20px 40px"},
    children=[

        # ── SECTION 1: HEADER ────────────────────────────────────────────────
        dbc.Row(dbc.Col(
            html.Div([
                html.Div([
                    html.Div(className="live-dot"),
                    html.Span("LIVE", style={
                        "fontSize": "0.65rem", "color": RED, "fontWeight": "700",
                        "marginLeft": "7px", "letterSpacing": "0.12em",
                    }),
                ], style={"display": "flex", "alignItems": "center", "marginBottom": "6px"}),
                html.H1("Iran Conflict — Economic Impact Dashboard",
                        className="dashboard-title"),
                html.P(
                    f"Conflict start: {CONFLICT_START}   |   Last data update: {LAST_UPDATE}",
                    className="dashboard-subtitle",
                ),
            ], style={"padding": "28px 0 16px"}),
        ), style={"borderBottom": f"1px solid {BORDER}", "marginBottom": "20px"}),

        # ── DATE RANGE PICKER (global filter for all charts) ─────────────────
        dbc.Row(dbc.Col(
            html.Div([
                html.Label("Filter date range:",
                           style={"color": TEXT_DIM, "fontSize": "0.78rem",
                                  "marginRight": "12px", "fontFamily": "system-ui"}),
                dcc.DatePickerRange(
                    id="date-picker",
                    min_date_allowed=DATE_MIN.date(),
                    max_date_allowed=DATE_MAX.date(),
                    start_date=DATE_MIN.date(),
                    end_date=DATE_MAX.date(),
                    display_format="YYYY-MM-DD",
                    style={"fontFamily": "system-ui"},
                ),
            ], style={"display": "flex", "alignItems": "center", "marginBottom": "18px"}),
        )),

        # ── SECTION 2: KPI ROW ───────────────────────────────────────────────
        dbc.Row([
            kpi_card("Brent Crude ($/bbl)", KPIS["brent"][0], KPIS["brent"][1], KPIS["brent"][2]),
            kpi_card("Gold ($/oz)",         KPIS["gold"][0],  KPIS["gold"][1],  KPIS["gold"][2]),
            kpi_card("VIX",                 KPIS["vix"][0],   KPIS["vix"][1],   KPIS["vix"][2]),
            kpi_card("DXY",                 KPIS["dxy"][0],   KPIS["dxy"][1],   KPIS["dxy"][2]),
            kpi_card("US 10Y Yield",        KPIS["us10y"][0], KPIS["us10y"][1], KPIS["us10y"][2]),
            kpi_card("2Y-10Y Spread",       KPIS["spread"][0],KPIS["spread"][1],KPIS["spread"][2]),
        ], className="g-2", style={"marginBottom": "20px"}),

        # ── SECTION 3: MAIN CHARTS ROW ───────────────────────────────────────
        dbc.Row([

            # Left: Indexed performance line chart + series dropdown
            dbc.Col(html.Div([
                html.H6("Indexed Performance Since D0 (= 100)", className="chart-title"),
                dcc.Dropdown(
                    id="series-dropdown",
                    options=INDEXED_OPTIONS,
                    value=DEFAULT_INDEXED,
                    multi=True,
                    className="dark-dropdown",
                    style={
                        "backgroundColor": BG_CARD,
                        "color": TEXT,
                        "border": f"1px solid {BORDER}",
                        "fontFamily": "system-ui",
                        "fontSize": "0.78rem",
                        "marginBottom": "8px",
                    },
                ),
                dcc.Graph(id="indexed-chart", config={"displayModeBar": False}),
            ], className="chart-card"), md=7),

            # Right: Equity total returns horizontal bar chart
            dbc.Col(html.Div([
                html.H6("Equity Index Returns Since D0 (%)", className="chart-title"),
                dcc.Graph(id="equity-bar-chart", config={"displayModeBar": False}),
            ], className="chart-card"), md=5),

        ], className="g-3", style={"marginBottom": "20px"}),

        # ── SECTION 4: BOTTOM ROW ────────────────────────────────────────────
        dbc.Row([

            # Left: Dual-axis Brent vs US 10Y yield (with range slider)
            dbc.Col(html.Div([
                html.H6("Brent Crude vs US 10Y Yield", className="chart-title"),
                dcc.Graph(id="dual-axis-chart", config={"displayModeBar": False}),
            ], className="chart-card"), md=6),

            # Right: Snapshot table — all key variables
            dbc.Col(html.Div([
                html.H6("Key Variables — Snapshot", className="chart-title"),
                dcc.Graph(id="snapshot-table", config={"displayModeBar": False}),
            ], className="chart-card"), md=6),

        ], className="g-3"),
    ],
)

# ─────────────────────────────────────────────────────────────────────────────
# SINGLE CALLBACK — all chart outputs driven by date range + series dropdown
# ─────────────────────────────────────────────────────────────────────────────
@app.callback(
    Output("indexed-chart",    "figure"),
    Output("equity-bar-chart", "figure"),
    Output("dual-axis-chart",  "figure"),
    Output("snapshot-table",   "figure"),
    Input("date-picker",       "start_date"),
    Input("date-picker",       "end_date"),
    Input("series-dropdown",   "value"),
)
def update_all(start_date, end_date, selected_series):
    start = pd.Timestamp(start_date) if start_date else DATE_MIN
    end   = pd.Timestamp(end_date)   if end_date   else DATE_MAX

    # ── CHART 1: Indexed performance line chart ──────────────────────────────
    fig_indexed = go.Figure()

    if not indexed_df.empty and selected_series:
        mask     = (indexed_df.index >= start) & (indexed_df.index <= end)
        filtered = indexed_df.loc[mask]

        for col in (selected_series or []):
            if col not in filtered.columns:
                continue
            s    = filtered[col].dropna()
            meta = SERIES_META.get(col, {"label": col, "color": BLUE})
            fig_indexed.add_trace(go.Scatter(
                x=s.index, y=s.values,
                name=meta["label"],
                mode="lines",
                line=dict(color=meta["color"], width=2),
                hovertemplate=f"<b>{meta['label']}</b><br>%{{x|%b %d, %Y}}: %{{y:.1f}}<extra></extra>",
            ))

    # D0 reference lines
    fig_indexed.add_hline(y=100, line_dash="dot", line_color="#3a3a3a", line_width=1)
    if start <= pd.Timestamp(CONFLICT_START) <= end:
        fig_indexed.add_vline(x=CONFLICT_START, line_dash="dash", line_color=RED, line_width=1)
        fig_indexed.add_annotation(
            x=CONFLICT_START, y=1, yref="paper",
            text="D0", font=dict(color=RED, size=10),
            showarrow=False, xanchor="left", xshift=4,
        )

    fig_indexed.update_layout(
        **CHART_BASE, height=370,
        yaxis_title="Index (D0 = 100)",
        hovermode="x unified",
        xaxis=dict(gridcolor=GRID, linecolor=BORDER, tickcolor=BORDER),
        yaxis=dict(gridcolor=GRID, linecolor=BORDER, tickcolor=BORDER),
    )

    # ── CHART 2: Equity returns horizontal bar ───────────────────────────────
    EQUITY_SERIES = [
        ("sp500",       "S&P 500",       equity_df),
        ("nasdaq",      "Nasdaq",        equity_df),
        ("eurostoxx50", "Euro Stoxx 50", equity_df),
        ("dax",         "DAX",           equity_df),
        ("ftse100",     "FTSE 100",      equity_df),
        ("nikkei225",   "Nikkei 225",    equity_df),
        ("shanghai",    "Shanghai",      equity_df),
    ]

    labels, values, bar_colors = [], [], []
    for col, label, src in EQUITY_SERIES:
        delta_col = f"{col}_delta_vs_d0_pct"
        if src.empty or delta_col not in src.columns:
            continue
        s = src.loc[src.index <= end, delta_col].dropna()
        if s.empty:
            continue
        v = float(s.iloc[-1])
        labels.append(label)
        values.append(v)
        bar_colors.append(RED if v < 0 else BLUE)

    # Sort ascending so largest positive is at top
    if values:
        pairs = sorted(zip(values, labels, bar_colors))
        values, labels, bar_colors = map(list, zip(*pairs))

    fig_equity = go.Figure(go.Bar(
        x=values, y=labels,
        orientation="h",
        marker_color=bar_colors,
        text=[f"{v:+.1f}%" for v in values],
        textposition="outside",
        textfont=dict(size=11, color=TEXT),
        hovertemplate="<b>%{y}</b><br>%{x:+.2f}%<extra></extra>",
    ))
    fig_equity.add_vline(x=0, line_color="#3a3a3a", line_width=1)
    fig_equity.update_layout(
        **CHART_BASE, height=370,
        showlegend=False,
        xaxis=dict(
            gridcolor=GRID, linecolor=BORDER, tickcolor=BORDER,
            ticksuffix="%", title="% change since D0",
        ),
        yaxis=dict(gridcolor=GRID, linecolor=BORDER, tickcolor=BORDER),
    )

    # ── CHART 3: Dual-axis Brent + US 10Y (with range slider) ───────────────
    fig_dual = make_subplots(specs=[[{"secondary_y": True}]])

    if not energy_df.empty and "brent_usd" in energy_df.columns:
        bm = (energy_df.index >= start) & (energy_df.index <= end)
        b  = energy_df.loc[bm, "brent_usd"].dropna()
        fig_dual.add_trace(
            go.Scatter(
                x=b.index, y=b.values, name="Brent ($/bbl)",
                line=dict(color=RED, width=2),
                hovertemplate="<b>Brent</b>: $%{y:.2f}<extra></extra>",
            ),
            secondary_y=False,
        )

    if not rates_df.empty and "us10y_yield" in rates_df.columns:
        rm = (rates_df.index >= start) & (rates_df.index <= end)
        r  = rates_df.loc[rm, "us10y_yield"].dropna()
        if not r.empty:
            fig_dual.add_trace(
                go.Scatter(
                    x=r.index, y=r.values, name="US 10Y (%)",
                    line=dict(color=BLUE, width=2, dash="dot"),
                    hovertemplate="<b>US 10Y</b>: %{y:.2f}%<extra></extra>",
                ),
                secondary_y=True,
            )

    fig_dual.update_layout(
        **CHART_BASE,
        height=370,
        hovermode="x unified",
    )
    fig_dual.update_xaxes(
        gridcolor=GRID, linecolor=BORDER, tickcolor=BORDER,
        rangeslider=dict(visible=True, bgcolor=BG_CARD, thickness=0.06),
    )
    fig_dual.update_yaxes(
        title_text="Brent ($/bbl)",
        gridcolor=GRID, linecolor=BORDER, tickcolor=BORDER,
        secondary_y=False,
    )
    fig_dual.update_yaxes(
        title_text="US 10Y Yield (%)",
        gridcolor=GRID, linecolor=BORDER, tickcolor=BORDER,
        showgrid=False,
        secondary_y=True,
    )

    # ── CHART 4: Snapshot table ──────────────────────────────────────────────
    t_labels, t_current, t_d7, t_d0 = [], [], [], []
    fc_current, fc_d7, fc_d0        = [], [], []

    for var in TABLE_VARS:
        col = var["col"]
        src = var["src"]
        bad_up = var["bad_up"]
        fmt    = var["fmt"]

        if src.empty or col not in src.columns:
            # Gracefully skip missing series (e.g. FRED data not loaded)
            continue

        s = src.loc[src.index <= end, col].dropna()
        if s.empty:
            continue

        cur_val = float(s.iloc[-1])
        t_labels.append(var["label"])
        t_current.append(f"{cur_val:{fmt}}")
        fc_current.append(TEXT)

        # Δ 7d — compare to latest value ≤ (last_date - 7 calendar days)
        cutoff = s.index[-1] - pd.Timedelta(days=7)
        s_prior = s[s.index <= cutoff]
        if not s_prior.empty:
            v7  = float(s_prior.iloc[-1])
            d7  = delta_pct(cur_val, v7)
            t_d7.append(fmt_delta(d7))
            fc_d7.append(risk_color(d7, bad_up))
        else:
            t_d7.append("N/A")
            fc_d7.append(TEXT_DIM)

        # Δ since D0 — from precomputed column
        d0_col = f"{col}_delta_vs_d0_pct"
        d0_val = safe_last(src, d0_col, as_of=end)
        t_d0.append(fmt_delta(d0_val))
        fc_d0.append(risk_color(d0_val, bad_up))

    # Row count for table height
    n_rows = max(len(t_labels), 1)

    fig_table = go.Figure(go.Table(
        columnwidth=[2.2, 1.1, 1.0, 1.2],
        header=dict(
            values=["<b>Variable</b>", "<b>Current</b>", "<b>Δ 7d</b>", "<b>Δ since D0</b>"],
            fill_color="#1e1e1e",
            font=dict(color=TEXT, size=12, family="system-ui"),
            align=["left", "right", "right", "right"],
            line_color=BORDER,
            height=28,
        ),
        cells=dict(
            values=[t_labels, t_current, t_d7, t_d0],
            fill_color=BG_CARD,
            # Per-cell conditional colors: list-of-lists, one per column
            font=dict(
                color=[fc_current, fc_current, fc_d7, fc_d0],
                size=11,
                family="system-ui",
            ),
            align=["left", "right", "right", "right"],
            line_color=BORDER,
            height=23,
        ),
    ))
    fig_table.update_layout(
        paper_bgcolor=BG_CHART,
        margin=dict(l=0, r=0, t=0, b=0),
        height=max(370, 28 + n_rows * 23 + 10),
    )

    return fig_indexed, fig_equity, fig_dual, fig_table


# ─────────────────────────────────────────────────────────────────────────────
# ENTRY POINT
# ─────────────────────────────────────────────────────────────────────────────
if __name__ == "__main__":
    app.run(debug=False, host="0.0.0.0", port=8050)
